[pytest]
testpaths = tests
addopts = --html=reports/reporte.html --self-contained-html -v
markers =
    smoke: Tests críticos del flujo principal
    exception: Tests de escenarios negativos y manejo de errores
log_cli = true
log_cli_level = INFO